version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - DIGITAL_OCEAN_TOKEN=${DIGITAL_OCEAN_TOKEN}
      - DIGITAL_OCEAN_SPACES_KEY=${DIGITAL_OCEAN_SPACES_KEY}
      - DIGITAL_OCEAN_SPACES_SECRET=${DIGITAL_OCEAN_SPACES_SECRET}
      - TEST_USER_ID=${TEST_USER_ID}
      - TEST_TENANT_ID=${TEST_TENANT_ID}
      - GODEPLOY_ACCESS_TOKEN=${GODEPLOY_ACCESS_TOKEN}
      - APP_URL=${APP_URL}
      - PORT=${PORT}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev
